---
resources:
  - name: opsmanager_client
    type: git
    source:
      uri: https://github.com/pivotal-cf-experimental/opsmanager_client
      branch: master

  - name: time-24hours
    type: time
    source:
      interval: 24h

jobs:
  - name: tests
    plan:
    - do:
      - aggregate:
        - get: opsmanager_client
          trigger: true
        - get: time-24hours
          trigger: true
      - task: run-tests
        file: opsmanager_client/ci/run-tests.yml
